// constants.js
export const ROLES = {
  ADMIN: 1,
  MANAGER: 2,
  STAFF: 3,
};

// Buat "Grup Izin" yang dinamis
export const PERMISSIONS = {
  // rool button CRUD
  CAN_ADD_USER: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_EDIT_USER: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_DELETE_USER: [ROLES.ADMIN, ROLES.MANAGER],

  CAN_ADD_BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_EDIT_BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_DELETE_BARANG: [ROLES.ADMIN, ROLES.MANAGER],

  CAN_GENERATE_REKAP: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],

  // CAN_VIEW_REPORT: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
};

// Definisikan akses untuk setiap item menu
export const MENU_ACCESS = {
  DASHBOARD: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
  BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  USERS: [ROLES.ADMIN],
  TRANSAKSI: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
  REPORTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
  LAPORAN_STOK: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
};
